project:
  type: website

website:
  title: "Future Forest Ecosystems Centre"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Who we are
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://....
          - text: Report a bug
            url: https://..../Issues
    side-bar:
      collapse-level: 4
      style: floating
  body-footer: |
    Powered by [Quarto](https://quarto.org/)

format:
  html:
    theme: minty
    toc: true
    html-math-method: katex

bibliography: references.bib

execute:
  freeze: auto