project:
  type: website
  render:
    - "*.qmd"
    - "!packages/"  ## there are some .Rmds in pkg files

website:
  title: "Future Forest Ecosystems Centre"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Who we are"
        file: about.qmd
      - text: "What we do"
        menu:
          - projects.qmd
          - products.qmd
      - text: "Publications"
        file: publications.qmd
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/bcgov/FFEC-website
          - text: Report a bug
            url: https://github.com/bcgov/FFEC-website/Issues
    side-bar:
      collapse-level: 4
      style: floating
  body-footer: |
    Powered by [Quarto](https://quarto.org/)

format:
  html:
    theme:
      - cosmo
      - scss/bcgov-theme.scss
    toc: true
    html-math-method: katex

bibliography: references.bib

execute:
  freeze: auto